### ISSUE TITLE
Referenced policy arrives unformatted

### ISSUE THREAD

**Issue by 464d41** [464d41/f5-waf-policy-editor#5]
Referenced policy arrives unformatted.

Try following reference for repro: ?ref=https://raw.githubusercontent.com/464d41/waf-policy-templates/master/policies/wordpress.json

<img width="1440" alt="Screen Shot 2021-06-24 at 11 34 48 AM" src="https://user-images.githubusercontent.com/23067500/123315240-5b08d380-d4e0-11eb-9224-1d8e218fa457.png">

**Comment by yoctoserge** [comment]
Addressed: badaf565192d2b5b6f14a51cc789a93083e383c8
